version: "3.8"

services:
  code-server:
    build:
      context: .
      dockerfile: .dockerfile
    image: matizo/code-server:custom
    restart: unless-stopped
    networks:
      - dokploy-network

    volumes:
      # Named volumes (serão criados localmente pelo Docker)
      - code_server_config:/config
      - code_server_projects:/home/coder/projects
      # Docker-in-Docker via socket do host
      - /var/run/docker.sock:/var/run/docker.sock
      # compartilha o binário do dokploy com a code server permitindo usar o comando Docker
      - /usr/bin/docker:/usr/bin/docker:ro

    # Adiciona o grupo Docker do host para acesso ao socket.
    # Para descobrir o GID correto, execute no host:
    #   getent group docker | cut -d: -f3
    group_add:
      - ${DOCKER_GID}

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - PASSWORD=${CODE_SERVER_PASSWORD}

    healthcheck:
      test: ["CMD", "curl", "-fsSL", "http://localhost:8443/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  code_server_config:
  code_server_projects:

networks:
  dokploy-network:
    external: true
